---
title: "<center>Uber Data Analysis<center>"
author: "<center>rahul<center>"
date: '<center>`r Sys.Date()`<center>'
output:
  prettydoc::html_pretty:
    toc: true
    theme: lumen
---

```{r import_packages, echo=FALSE, warning=FALSE, comment=NA, message=FALSE}
library(tidyverse)
library(ggplot2)
library(DT)
library(dplyr)
library(plotly)
library(lubridate)
library(scales)
library(tinytex)
```

```{r import_data, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
uber_april_dataset <- read.delim("/home/rahul/Downloads/uber-raw-data-apr14.csv", sep = ",", header = TRUE)
uber_may_dataset <- read.delim("/home/rahul/Downloads/uber-raw-data-may14.csv", sep = ",", header = TRUE)
uber_june_dataset <- read.delim("/home/rahul/Downloads/uber-raw-data-jun14.csv", sep = ",", header = TRUE)

uber_dataset <- rbind(uber_april_dataset, uber_may_dataset, uber_june_dataset)
```

```{r color_code, echo = FALSE, warning = FALSE, comment = NA, message = FALSE }
colors <- c("#CC1011", "#665555", "#05a399", "#cfcaca", "#f5e840", "#0683c9", "#e075b0")
```


```{r convert_into_readable_format, echo = FALSE, warning = FALSE, comment = NA, message = FALSE }
uber_dataset$Date.Time <- as.POSIXct(uber_dataset$Date.Time, format= "%m/%d/%Y %H:%M:%S")
uber_dataset$Time <- format(as.POSIXct(uber_dataset$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")
uber_dataset$Date.Time <- ymd_hms(uber_dataset$Date.Time)

```

```{r individual_columns_for_month_and_year, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
uber_dataset$day <- factor(day(uber_dataset$Date.Time))
uber_dataset$month <- factor(month(uber_dataset$Date.Time, label = TRUE))
uber_dataset$year <- factor(year(uber_dataset$Date.Time))
uber_dataset$day_of_week <- factor(wday(uber_dataset$Date.Time, label = TRUE))
```

```{r time_variables, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
uber_dataset$second <- factor(second(hms(uber_dataset$Time)))
uber_dataset$minute <- factor(minute(hms(uber_dataset$Time)))
uber_dataset$hour <- factor(hour(hms(uber_dataset$Time)))
```


```{r trips_by_hours_in_a_day, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
hourly_data <- as.data.frame(table(uber_dataset['hour']))
names(hourly_data)[2] <- c("Total")
```

```{r trips_by_hours_in_a_day_table, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
DT::datatable(hourly_data, rownames = FALSE)
```


```{r data_by_hour_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
hourly_data_plot <- ggplot(hourly_data, aes(x = `hour`, `Total`, fill = hour)) + geom_bar(stat = "identity") + ggtitle("Trips Every Hour") + theme(legend.position = "none", plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + scale_y_continuous(labels=comma)
ggplotly(hourly_data_plot)
```

```{r trips_by_month, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
monthly_data <- as.data.frame(table(uber_dataset['month']))
names(monthly_data)[2] <- c("Total")
```

```{r trips_by_month_table, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
DT::datatable(monthly_data, rownames = FALSE)
```


```{r data_month_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
monthly_data_plot <- ggplot(monthly_data, aes(x = `month`, `Total`, fill = month)) + geom_bar(stat = "identity") + ggtitle("Trips monthly") + theme(legend.position = "none", plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + scale_y_continuous(labels=comma)
ggplotly(monthly_data_plot)
```


```{r trips_by_day_of_week, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
day_of_week_data <- as.data.frame(table(uber_dataset['day_of_week']))
names(day_of_week_data)[2] <- c("Total")
```

```{r trips_by_day_of_week_table, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
DT::datatable(day_of_week_data, rownames = FALSE)
```


```{r data_day_of_week_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
day_data_of_week_plot <- ggplot(day_of_week_data, aes(x = `day_of_week`, `Total`, fill = day_of_week)) + geom_bar(stat = "identity") + ggtitle("Trips days of week") + theme(legend.position = "none", plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + scale_y_continuous(labels=comma)
ggplotly(day_data_of_week_plot)
```

```{r trips_by_day, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
day_data <- as.data.frame(table(uber_dataset['day']))
names(day_data)[2] <- c("Total")
```

```{r trips_by_day_table, echo = FALSE, warning = FALSE, comment = NA, message = FALSE}
DT::datatable(day_data, rownames = FALSE)
```


```{r data_day_plot, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
day_data_plot <- ggplot(day_data, aes(x = `day`, `Total`, fill = day)) + geom_bar(stat = "identity") + ggtitle("Trips per day") + theme(legend.position = "none", plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + scale_y_continuous(labels=comma)
ggplotly(day_data_plot)
```


# **Heatmap visualization of day, hour and month**

```{r heatmap_per_day, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
heatmap_per_day_plot <- ggplot(uber_dataset, aes(day, hour)) + geom_tile(color = "white") + ggtitle("Heat Map by Hour and Day")
heatmap_per_day_plot
```

```{r heatmap_month_day, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
heatmap_per_month_plot <- ggplot(uber_dataset, aes(day, month)) + geom_tile(color = "white") + ggtitle("Heat Map by Month and Day")
heatmap_per_month_plot
```


```{r heatmap_day_of_week, echo = FALSE, warning = FALSE, comment = NA, message = FALSE, out.width="930px",out.height="500px"}
heatmap_per_day_of_week_plot <- ggplot(uber_dataset, aes(day_of_week, month)) + geom_tile(color = "white") + ggtitle("Heat Map by Month and Day")
heatmap_per_day_of_week_plot
```
